# Generated by Django 3.2 on 2024-11-28 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteVet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=80)),
                ('rut', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=50)),
                ('sexo_mascota', models.CharField(max_length=10)),
                ('edad_mascota', models.IntegerField()),
                ('especie_mascota', models.CharField(max_length=60)),
                ('raza_mascota', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CitaMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('motivo_cita', models.CharField(max_length=500)),
                ('remedio_cita', models.CharField(max_length=100)),
                ('dato_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.clientevet')),
                ('dato_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.mascota')),
            ],
        ),
    ]
