# Generated by Django 3.2 on 2024-12-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0002_veterinario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazaPerro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('nombre_cientifico', models.CharField(max_length=100)),
                ('edad_aprox_vida', models.CharField(max_length=20)),
                ('alimentacion', models.CharField(max_length=255)),
                ('tiempo_paseo', models.CharField(max_length=100)),
                ('dato_curioso', models.TextField()),
                ('recomendacion', models.TextField()),
            ],
        ),
    ]
