# Generated by Django 3.2 on 2024-12-18 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0003_razaperro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razaperro',
            name='alimentacion',
            field=models.CharField(help_text="Por ejemplo: 'Croquetas, carne, vegetales'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='razaperro',
            name='animal',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Otro', 'Otro')], default='Perro', help_text="Selecciona 'Perro' u 'Otro'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='razaperro',
            name='dato_curioso',
            field=models.TextField(help_text='Un dato interesante sobre la raza.'),
        ),
        migrations.AlterField(
            model_name='razaperro',
            name='edad_aprox_vida',
            field=models.PositiveIntegerField(help_text='Edad aproximada de vida en años (máximo 18).', validators=[django.core.validators.MinValueValidator(0, 'La edad debe ser un número positivo.'), django.core.validators.MaxValueValidator(18, 'La edad máxima permitida es 18 años.')]),
        ),
        migrations.AlterField(
            model_name='razaperro',
            name='nombre_cientifico',
            field=models.CharField(help_text="Por ejemplo: 'Canis lupus familiaris'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='razaperro',
            name='raza',
            field=models.CharField(help_text="Por ejemplo: 'Labrador'. Este nombre debe ser único.", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='razaperro',
            name='recomendacion',
            field=models.TextField(help_text='Recomendaciones para el cuidado de la raza.'),
        ),
        migrations.AlterField(
            model_name='razaperro',
            name='tiempo_paseo',
            field=models.CharField(help_text="Por ejemplo: '30 minutos diarios'.", max_length=100),
        ),
    ]
