# Generated by Django 3.2 on 2024-12-19 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0004_auto_20241218_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Razas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], default='Perro', help_text="Selecciona 'Perro', 'Gato' u 'Otro'.", max_length=50)),
                ('raza', models.CharField(help_text="Por ejemplo: 'Labrador' o 'Siamese'. Este nombre debe ser único.", max_length=50, unique=True)),
                ('nombre_cientifico', models.CharField(help_text="Por ejemplo: 'Canis lupus familiaris' o 'Felis catus'.", max_length=100)),
                ('edad_aprox_vida', models.PositiveIntegerField(help_text='Edad aproximada de vida en años (máximo 30).', validators=[django.core.validators.MinValueValidator(0, 'La edad debe ser un número positivo.'), django.core.validators.MaxValueValidator(30, 'La edad máxima permitida es 30 años.')])),
                ('alimentacion', models.CharField(help_text="Por ejemplo: 'Croquetas, carne, vegetales' para perros o 'Pienso, carne' para gatos.", max_length=255)),
                ('tiempo_paseo', models.CharField(help_text="Por ejemplo: '30 minutos diarios' para perros o 'Jugar en casa' para gatos.", max_length=100)),
                ('dato_curioso', models.TextField(help_text='Un dato interesante sobre la raza.')),
                ('recomendacion', models.TextField(help_text='Recomendaciones para el cuidado de la raza.')),
            ],
        ),
        migrations.DeleteModel(
            name='RazaPerro',
        ),
    ]
