# Generated by Django 3.2 on 2024-12-19 00:20

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0005_auto_20241218_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='raza_mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.razas'),
        ),
    ]
