# Generated by Django 3.2 on 2024-12-19 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0006_alter_mascota_raza_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='raza_mascota',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='direccion',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, 'La dirección debe tener al menos 5 caracteres.')], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator('Por favor, ingrese un correo electrónico válido.')], verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='especialidad',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'La especialidad debe tener al menos 3 caracteres.')], verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='nombre_veterinario',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'El nombre debe tener al menos 2 caracteres.')], verbose_name='Nombre del veterinario'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos, y puede incluir un prefijo internacional opcional.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
    ]
