# Generated by Django 3.2 on 2024-12-20 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0007_auto_20241219_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientevet',
            name='apellido',
            field=models.CharField(max_length=45, validators=[django.core.validators.RegexValidator(message='El apellido solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='clientevet',
            name='direccion',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10, 'La dirección debe tener al menos 10 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='clientevet',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este correo electrónico ya está registrado.'}, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='clientevet',
            name='nombre',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='clientevet',
            name='rut',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12.345.678-K.', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$')]),
        ),
        migrations.AlterField(
            model_name='clientevet',
            name='telefono',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 9 y 12 dígitos.', regex='^\\d{9,12}$')]),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator('Por favor, ingrese un correo electrónico válido.')], verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='nombre_veterinario',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'El nombre debe tener al menos 2 caracteres.')], verbose_name='Nombre del veterinario'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='telefono',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos, y puede incluir un prefijo internacional opcional.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
    ]
