# Generated by Django 3.2 on 2025-07-21 22:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0008_auto_20241220_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='citamascota',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appVeterinaria.veterinario'),
        ),
        migrations.AlterField(
            model_name='citamascota',
            name='motivo_cita',
            field=models.CharField(choices=[('control', 'Control'), ('urgencia', 'Urgencia'), ('rutina', 'Rutina'), ('primer_control', 'Primer Control'), ('operacion', 'Operación')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='citamascota',
            name='remedio_cita',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie_mascota',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], max_length=60),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo_mascota',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10),
        ),
        migrations.AlterField(
            model_name='razas',
            name='alimentacion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='razas',
            name='dato_curioso',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='razas',
            name='edad_aprox_vida',
            field=models.PositiveIntegerField(help_text='Edad aproximada de vida en años (máximo 30).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='razas',
            name='recomendacion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='razas',
            name='tiempo_paseo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='direccion',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='especialidad',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='nombre_veterinario',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre del veterinario'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='telefono',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='citamascota',
            name='remedio_cita',
            field=models.ManyToManyField(to='appVeterinaria.Remedio'),
        ),
    ]
