# Generated by Django 3.2 on 2025-07-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0009_auto_20250721_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedio',
            name='animal',
            field=models.CharField(blank=True, choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], default='Perro', help_text='Seleccione el tipo de animal al que va dirigido el remedio.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='remedio',
            name='frecuencia',
            field=models.CharField(blank=True, default='Una vez al día', help_text='Ej: Cada 8 horas, una vez al día, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='remedio',
            name='uso_recomendado',
            field=models.TextField(blank=True, default='No especificado', help_text='¿Para qué se recomienda este remedio?', null=True),
        ),
    ]
