# Generated by Django 5.2.8 on 2025-11-17 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0010_auto_20250721_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='especialidad',
            field=models.CharField(choices=[('Perros', 'Perros'), ('Gatos', 'Gatos'), ('Otros', 'Otros')], max_length=100, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='nombre_veterinario',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombres y Apellidos'),
        ),
    ]
