# Generated by Django 4.2.7 on 2025-12-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0011_alter_veterinario_especialidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Veterinario', 'Veterinario')], max_length=45)),
            ],
            options={
                'verbose_name': 'Usuario del Sistema',
                'verbose_name_plural': 'Usuarios del Sistema',
                'ordering': ['username'],
            },
        ),
    ]
