# Generated by Django 4.2.7 on 2025-12-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0012_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamascota',
            name='remedio_cita',
            field=models.ManyToManyField(blank=True, to='appVeterinaria.remedio'),
        ),
    ]
