# Generated by Django 4.2.7 on 2025-12-15 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0013_alter_citamascota_remedio_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad_mascota',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='La edad no puede ser negativa.'), django.core.validators.MaxValueValidator(30, message='La edad no puede ser mayor a 30 años.')]),
        ),
    ]
